NULL

#' @importFrom grid grid.circle gpar
draw_bubble <- function(m, m_prop,
                        col = \(x) "black",
                        fill = \(x) NA,
                        dot_scale = 0.9,
                        show_max = TRUE) {

  function(j, i, x, y, width, height, fill) {

    if (isTRUE(show_max) && !any(is.na(c(m[i, j], m_prop[i, j])))) {
      grid.circle(x = x,
                  y = y,
                  r = dot_scale * (min(c(width, height)) / 2),
                  gp = gpar(col = "gray")
      )
    }
    grid.circle(x = x,
                y = y,
                r = m_prop[i, j] * dot_scale * (min(c(width, height)) / 2),
                gp = gpar(col = col(m[i, j]),
                          fill = fill(m[i, j])
                ))
  }
}

#' Draw a bubble heatmap.
#'
#' @importFrom tidyr pivot_wider
#' @importFrom tibble column_to_rownames
#' @importFrom tidyselect eval_select
#' @importFrom rlang enquo as_name
#' @importFrom ComplexHeatmap Heatmap
#'
#' @param data A tibble containing a "long version" of values and proportions
#' @param row,col The variables to be used as columns and rows to represent the matrix
#' @param colour,size The variables that will be mapped to the heatmap colour intensity and the dot size
#' @param row_key,col_key An optional variable to split the columns and rows (groups)
#' @param colour_scale A colour mapping function such as generated by \code{circlize::colorRamp2}.
#' @param dot_size The maximum size of the dot/cell of the heatmap.
#' @param dot_scale A scaling factor to avoid dots to touch each other (defaults to 0.9).
#' @param ... Other arguments passed to \code{ComplexHeatmap::Heatmap}
#' @return a ComplexHeatmap
#' @export
bubble_heatmap <- function(data,
                           row, col,
                           colour, size,
                           row_key = NULL,
                           col_key = NULL,
                           colour_scale = circlize::colorRamp2(
                             breaks = c(-2, 0, 2),
                             colors = c("#377EB8", "white", "#E41A1C")
                           ),
                           dot_size = unit(5, "mm"),
                           dot_scale = 0.9,
                           ...) {

  m <-  pivot_wider(data,
                    names_from = {{col}},
                    values_from = {{colour}},
                    id_cols = {{row}}) |>
    column_to_rownames(as_name(enquo(row))) |>
    as.matrix()

  m_prop <- pivot_wider(data,
                        names_from = {{col}},
                        values_from = {{size}},
                        id_cols = {{row}}) |>
    column_to_rownames(as_name(enquo(row))) |>
    as.matrix()

  n_col_keys <- length(eval_select(enquo(col_key), data))
  n_row_keys <- length(eval_select(enquo(row_key), data))

  stopifnot(n_col_keys <= 1 && n_row_keys <= 1)

  if (n_col_keys > 0) {
    col_key <- distinct(data, {{col}}, {{col_key}}) |>
      deframe()
  }

  if (n_row_keys > 0) {
    row_key <- distinct(data, {{row}}, {{row_key}}) |>
      deframe()
  }

  Heatmap(m,
          name = "z-score",
          col = colour_scale,
          rect_gp = gpar(type = "none"),
          column_title_rot = 90,
          row_title_rot = 0,
          show_column_dend = FALSE,
          show_row_dend = FALSE,
          heatmap_legend_param = list(direction = "horizontal"),

          cell_fun = draw_bubble(m, m_prop,
                                 fill = {{colour_scale}},
                                 dot_scale = {{dot_scale}}),
          border_gp = gpar(col = "gray", lty = 1),
          column_split = col_key,
          row_split = row_key,
          width = ncol(m) * dot_size,
          height = nrow(m) * dot_size,
          ...)
}
